-- StudyAbroadOS Supabase schema
-- Run this file in Supabase Dashboard > SQL Editor.
-- It stores all business data in Postgres and isolates rows by auth.uid().

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  target_intake text,
  name text,
  undergraduate_major text,
  grade text,
  current_gpa numeric default 0,
  gpa_scale numeric default 4,
  toefl_current integer default 0,
  toefl_target integer default 0,
  gre_gmat_status text,
  target_regions text,
  target_majors text,
  budget_range text,
  internships text,
  research_experience text,
  competitions_projects text,
  tutoring_part_time text,
  stock_investment text,
  career_goals text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  region text,
  school_name text not null,
  program_name text not null,
  degree_type text,
  academic_direction text,
  website text,
  source_url text,
  verified_date date,
  is_shared boolean not null default false,
  tuition numeric default 0,
  living_cost numeric default 0,
  application_fee numeric default 0,
  deadline date,
  gpa_requirement text,
  toefl_requirement text,
  gre_gmat_requirement text,
  recommendation_requirement text,
  essay_requirement text,
  scholarship_available boolean default false,
  employment_notes text,
  category text,
  status text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.programs add column if not exists source_url text;
alter table public.programs add column if not exists verified_date date;
alter table public.programs add column if not exists is_shared boolean not null default false;

create table if not exists public.application_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_name text not null,
  related_program text,
  task_type text,
  deadline date not null,
  priority text,
  status text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.writing_materials (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  experience_name text not null,
  experience_type text,
  period text,
  background text,
  action text,
  result text,
  abilities text,
  usage text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  program_ref text not null,
  application_fee numeric default 0,
  score_report_fee numeric default 0,
  tuition numeric default 0,
  living_cost numeric default 0,
  visa_flight_estimate numeric default 0,
  scholarship_amount numeric default 0,
  total_cost numeric default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Optional tutor/workbench tables for student tutoring scenarios.
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  grade text,
  current_score numeric,
  target_score numeric,
  school_region text,
  current_chapter text,
  main_problems text,
  parent_concerns text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  class_date date not null,
  duration numeric default 2,
  topic text,
  performance text,
  completion text,
  next_focus text,
  feedback_sent boolean default false,
  prepared boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mistakes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  mistake_date date not null,
  chapter text,
  description text,
  reason text,
  knowledge_point text,
  repeated boolean default false,
  next_suggestion text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  course_id bigint references public.courses(id) on delete set null,
  feedback_date date not null,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.incomes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_id bigint references public.students(id) on delete cascade,
  class_date date not null,
  hours numeric not null,
  unit_price numeric not null,
  amount numeric not null,
  paid boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_user_id on public.profiles(user_id);
create index if not exists idx_programs_user_id_deadline on public.programs(user_id, deadline);
create index if not exists idx_programs_shared_deadline on public.programs(is_shared, deadline);
create index if not exists idx_tasks_user_id_deadline on public.application_tasks(user_id, deadline);
create index if not exists idx_materials_user_id on public.writing_materials(user_id);
create index if not exists idx_budgets_user_id on public.budgets(user_id);
create index if not exists idx_students_user_id on public.students(user_id);
create index if not exists idx_courses_user_id_date on public.courses(user_id, class_date);
create index if not exists idx_mistakes_user_id_date on public.mistakes(user_id, mistake_date);
create index if not exists idx_feedbacks_user_id_date on public.feedbacks(user_id, feedback_date);
create index if not exists idx_incomes_user_id_date on public.incomes(user_id, class_date);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_programs_updated_at on public.programs;
create trigger set_programs_updated_at before update on public.programs
for each row execute function public.set_updated_at();

drop trigger if exists set_application_tasks_updated_at on public.application_tasks;
create trigger set_application_tasks_updated_at before update on public.application_tasks
for each row execute function public.set_updated_at();

drop trigger if exists set_writing_materials_updated_at on public.writing_materials;
create trigger set_writing_materials_updated_at before update on public.writing_materials
for each row execute function public.set_updated_at();

drop trigger if exists set_budgets_updated_at on public.budgets;
create trigger set_budgets_updated_at before update on public.budgets
for each row execute function public.set_updated_at();

drop trigger if exists set_students_updated_at on public.students;
create trigger set_students_updated_at before update on public.students
for each row execute function public.set_updated_at();

drop trigger if exists set_courses_updated_at on public.courses;
create trigger set_courses_updated_at before update on public.courses
for each row execute function public.set_updated_at();

drop trigger if exists set_mistakes_updated_at on public.mistakes;
create trigger set_mistakes_updated_at before update on public.mistakes
for each row execute function public.set_updated_at();

drop trigger if exists set_feedbacks_updated_at on public.feedbacks;
create trigger set_feedbacks_updated_at before update on public.feedbacks
for each row execute function public.set_updated_at();

drop trigger if exists set_incomes_updated_at on public.incomes;
create trigger set_incomes_updated_at before update on public.incomes
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.programs enable row level security;
alter table public.application_tasks enable row level security;
alter table public.writing_materials enable row level security;
alter table public.budgets enable row level security;
alter table public.students enable row level security;
alter table public.courses enable row level security;
alter table public.mistakes enable row level security;
alter table public.feedbacks enable row level security;
alter table public.incomes enable row level security;

drop policy if exists profiles_select_own on public.profiles;
drop policy if exists profiles_insert_own on public.profiles;
drop policy if exists profiles_update_own on public.profiles;
drop policy if exists profiles_delete_own on public.profiles;
create policy profiles_select_own on public.profiles for select using (auth.uid() = user_id);
create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = user_id);
create policy profiles_update_own on public.profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy profiles_delete_own on public.profiles for delete using (auth.uid() = user_id);

drop policy if exists programs_select_own on public.programs;
drop policy if exists programs_select_accessible on public.programs;
drop policy if exists programs_insert_own on public.programs;
drop policy if exists programs_update_own on public.programs;
drop policy if exists programs_delete_own on public.programs;
create policy programs_select_accessible on public.programs
for select using (
  auth.uid() = user_id
  or (auth.role() = 'authenticated' and is_shared = true)
);
create policy programs_insert_own on public.programs for insert with check (auth.uid() = user_id);
create policy programs_update_own on public.programs for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy programs_delete_own on public.programs for delete using (auth.uid() = user_id);

drop policy if exists application_tasks_select_own on public.application_tasks;
drop policy if exists application_tasks_insert_own on public.application_tasks;
drop policy if exists application_tasks_update_own on public.application_tasks;
drop policy if exists application_tasks_delete_own on public.application_tasks;
create policy application_tasks_select_own on public.application_tasks for select using (auth.uid() = user_id);
create policy application_tasks_insert_own on public.application_tasks for insert with check (auth.uid() = user_id);
create policy application_tasks_update_own on public.application_tasks for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy application_tasks_delete_own on public.application_tasks for delete using (auth.uid() = user_id);

drop policy if exists writing_materials_select_own on public.writing_materials;
drop policy if exists writing_materials_insert_own on public.writing_materials;
drop policy if exists writing_materials_update_own on public.writing_materials;
drop policy if exists writing_materials_delete_own on public.writing_materials;
create policy writing_materials_select_own on public.writing_materials for select using (auth.uid() = user_id);
create policy writing_materials_insert_own on public.writing_materials for insert with check (auth.uid() = user_id);
create policy writing_materials_update_own on public.writing_materials for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy writing_materials_delete_own on public.writing_materials for delete using (auth.uid() = user_id);

drop policy if exists budgets_select_own on public.budgets;
drop policy if exists budgets_insert_own on public.budgets;
drop policy if exists budgets_update_own on public.budgets;
drop policy if exists budgets_delete_own on public.budgets;
create policy budgets_select_own on public.budgets for select using (auth.uid() = user_id);
create policy budgets_insert_own on public.budgets for insert with check (auth.uid() = user_id);
create policy budgets_update_own on public.budgets for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy budgets_delete_own on public.budgets for delete using (auth.uid() = user_id);

drop policy if exists students_select_own on public.students;
drop policy if exists students_insert_own on public.students;
drop policy if exists students_update_own on public.students;
drop policy if exists students_delete_own on public.students;
create policy students_select_own on public.students for select using (auth.uid() = user_id);
create policy students_insert_own on public.students for insert with check (auth.uid() = user_id);
create policy students_update_own on public.students for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy students_delete_own on public.students for delete using (auth.uid() = user_id);

drop policy if exists courses_select_own on public.courses;
drop policy if exists courses_insert_own on public.courses;
drop policy if exists courses_update_own on public.courses;
drop policy if exists courses_delete_own on public.courses;
create policy courses_select_own on public.courses for select using (auth.uid() = user_id);
create policy courses_insert_own on public.courses for insert with check (auth.uid() = user_id);
create policy courses_update_own on public.courses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy courses_delete_own on public.courses for delete using (auth.uid() = user_id);

drop policy if exists mistakes_select_own on public.mistakes;
drop policy if exists mistakes_insert_own on public.mistakes;
drop policy if exists mistakes_update_own on public.mistakes;
drop policy if exists mistakes_delete_own on public.mistakes;
create policy mistakes_select_own on public.mistakes for select using (auth.uid() = user_id);
create policy mistakes_insert_own on public.mistakes for insert with check (auth.uid() = user_id);
create policy mistakes_update_own on public.mistakes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy mistakes_delete_own on public.mistakes for delete using (auth.uid() = user_id);

drop policy if exists feedbacks_select_own on public.feedbacks;
drop policy if exists feedbacks_insert_own on public.feedbacks;
drop policy if exists feedbacks_update_own on public.feedbacks;
drop policy if exists feedbacks_delete_own on public.feedbacks;
create policy feedbacks_select_own on public.feedbacks for select using (auth.uid() = user_id);
create policy feedbacks_insert_own on public.feedbacks for insert with check (auth.uid() = user_id);
create policy feedbacks_update_own on public.feedbacks for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy feedbacks_delete_own on public.feedbacks for delete using (auth.uid() = user_id);

drop policy if exists incomes_select_own on public.incomes;
drop policy if exists incomes_insert_own on public.incomes;
drop policy if exists incomes_update_own on public.incomes;
drop policy if exists incomes_delete_own on public.incomes;
create policy incomes_select_own on public.incomes for select using (auth.uid() = user_id);
create policy incomes_insert_own on public.incomes for insert with check (auth.uid() = user_id);
create policy incomes_update_own on public.incomes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy incomes_delete_own on public.incomes for delete using (auth.uid() = user_id);
